/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Jkong_square_PrintSquare */

#ifndef _Included_com_Jkong_square_PrintSquare
#define _Included_com_Jkong_square_PrintSquare
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Jkong_square_PrintSquare
 * Method:    printsqr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_Jkong_square_PrintSquare_printsqr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
