/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mlist */

#ifndef _Included_mlist
#define _Included_mlist
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mlist
 * Method:    printlist
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mlist_printlist
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
